//Aca se describe lo que pasa en la app
export const AGREGAR_PRODUCTO = 'AGREGAR_PRODUCTO';
export const AGREGAR_PRODUCTO_EXITO = 'AGREGAR_PRODUCTO_EXITO';
export const AGREGAR_PRODUCTO_ERROR = 'AGREGAR_PRODUCTO_ERROR';

export const COMENZAR_DESCARGA_PRODUCTO = 'COMENZAR_DESCARGA_PRODUCTO';
export const DESCARGA_PRODUCTO_EXITO = 'DESCARGA_PRODUCTO_EXITO';
export const DESCARGA_PRODUCTO_ERROR = 'DESCARGA_PRODUCTO_ERROR';